improve pre-commit hook

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -16,24 +16,23 @@ then
 fi
 SFILES=${SFILES:-$STAGED_FILES_CMD}
 
-echo "------------------------------"
-echo "Checking PHP Lint..."
-echo "------------------------------"
-for FILE in $SFILES
-do
-	php -l -d display_errors=0 ${PROJECTROOT}${FILE}
-	if [ $? != 0 ]
-	then
-		echo "Fix the error in ${PROJECTROOT}${FILE} before commit."
-		exit 1
-	fi
-	FILES="$FILES ${PROJECTROOT}${FILE}"
-done
-
-
 if [ "$FILES" != "" ]
 then
-	echo "------------------------------"
+    echo "------------------------------"
+    echo "Checking PHP Lint..."
+    echo "------------------------------"
+    for FILE in $SFILES
+    do
+        php -l -d display_errors=0 ${PROJECTROOT}${FILE}
+        if [ $? != 0 ]
+        then
+            echo "Fix the error in ${PROJECTROOT}${FILE} before commit."
+            exit 1
+        fi
+        FILES="$FILES ${PROJECTROOT}${FILE}"
+    done
+
+    echo "------------------------------"
 	echo "Running Code standard fixer..."
 	echo "------------------------------"
     for FILE in $SFILES
